version: '3.3'
services:
  api_server:
    image: myorg/myapp:latest
    ports:
      - 8080:8081
  mysql:
    image: mysql:5.7.21
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - sail
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    ports:
      - 8082:80
    networks:
      - sail
networks:
    sail:
        driver: bridge
